### ISSUE TITLE
Caption for WAV display

### ISSUE THREAD

**Issue by rmsrosa** [dancasimiro/WAV.jl#100]
Hi,

For my notebooks, I added a composite type similar to `WAVArray` which adds a "caption" field, which is then used in `show` to display a caption in an html figure element wrapping the html audio controls. 

Ideally, it should replace the existing `WAVArray`, but that could be a breaking change, so I made it into a new struct `CWAVArray`, also for the lack of a better name.

It doesn't look well in the same cell as `WAVArray`, due to the identation, but one can use `CWAVArray` with the empty string if no caption is desired.

If you like the idea, I could make a PR with the above.  Let me know.

This is essentially it:

```julia
struct CWAVArray{T,N}
    Fs::Number
    data::AbstractArray{T,N}
    caption::AbstractString
end

CWAVArray(Fs::Number, data::AbstractArray) = CWAVArray(Fs, data, "")

wavwrite(x::CWAVArray, io::IO) = wavwrite(x.data, io; Fs=x.Fs)

function show(io::IO, ::MIME"text/html", x::CWAVArray)
    buf = IOBuffer()
    wavwrite(x, buf)
    data = base64encode(String(take!(copy(buf))))
    markup = """<figure>
                $(ifelse(x.caption !== "", "<figcaption>$(x.caption)</figcaption>", ""))
                <audio controls="controls" {autoplay}>
                <source src="data:audio/wav;base64,$data" type="audio/wav" />
                Your browser does not support the audio element.
                </audio>
                </figure>"""
    print(io, markup)
end
```

And here is how it displays in a jupyter notebook, including the case with an empty caption:

<img width="754" alt="instruments" src="https://user-images.githubusercontent.com/17986148/121814753-19a73700-cc49-11eb-9835-3e90f037dcd2.png">

<img width="772" alt="sinewaves" src="https://user-images.githubusercontent.com/17986148/121814757-1f048180-cc49-11eb-90d2-109c6f154eb6.png">

<img width="761" alt="nocaption" src="https://user-images.githubusercontent.com/17986148/121814762-23309f00-cc49-11eb-9097-30722088702f.png">

**Comment by dancasimiro** [comment]
@rmsrosa This looks like a nice addition. Could you help me understand why you cannot extend the existing `WAVArray` type? I'm probably missing some obvious detail, but it seems like this functionality could be added without breaking the API.

**Comment by rmsrosa** [comment]
Yeah, I guess it doesn't break it. It adds a field, but it should be fine with the constructor that only takes the first two fields.

Should I make a PR?

**Comment by dancasimiro** [comment]
> Yeah, I guess it doesn't break it. It adds a field, but it should be fine with the constructor that only takes the first two fields.
> 
> Should I make a PR?

Yes, please! A PR would be very much appreciated.
