### ISSUE TITLE
Extra \0 bytes in RIFF INFO tags causes wav_info_read() to raise ArgumentError

### ISSUE THREAD

**Issue by cHemingway** [dancasimiro/WAV.jl#101]
I am trying to read a file where extra padding/termination bytes are present in the RIFF INFO tags, so `wav_info_read(chunks)` throws an exception.
```
ERROR: LoadError: ArgumentError: Symbol name may not contain \0
Stacktrace:
 [1] Symbol
   @ .\boot.jl:480 [inlined]
 [2] read_tag(tags::Dict{Symbol, String}, t::Vector{UInt8})
   @ WAV [snipped]\WAV\src\WAVChunk.jl:210
 [3] wav_info_read(chunks::Vector{WAVChunk})
   @ WAV [snipped]\WAV\src\WAVChunk.jl:250
```
This appears to be because the (private) function [read_tag](../blob/249b0723e08a98680d4433e3946da1c09aee52d2/src/WAVChunk.jl#L209) does not skip over multiple '\0' characters before returning the new list_data t.
Instead, it calls `return t[(i+1):end]` which would only skip one character. 
On the next call to `read_tag()`, the first line of the function will then attempt to execute:
```julia
tag_id = Symbol(String("\0ABC"))
```
which will raise the ArgumentError as shown before.

I think I have a working fix for this, and will submit it as a pull request.

**Comment by CMGeldenhuys** [comment]
An alternative fix might be to utilise the _size_ field present in the subchunk block. This would allow one to skip arbitrary bytes instead of relying on the string being null padded beyond its null termination.

**Comment by cHemingway** [comment]
That fix looks better to me! I should have seen the `size` field
