### ISSUE TITLE
Not able to read this wav file

### ISSUE THREAD

**Issue by kinord** [dancasimiro/WAV.jl#18]
I tried reading the attached wav file, but it did not work. I am able to read other .wav files. GitHub does not allow for attaching wav files, so I changed the extension to .png. You will need to rename the attached file back to .wav.

![sample](https://cloud.githubusercontent.com/assets/10521259/5728365/88c25c22-9b1e-11e4-8121-f3295ae333a2.png)

I'm running Julia 0.3.5 in JuliaBox. I also had the same trouble running Julia 0.3.3 in linux.

Steps to reproduce:

julia> using WAV
julia> y = wavread("sample.wav")

Error message:

in read! at iostream.jl:196
in wavread at /home/juser/.julia/v0.3/WAV/src/WAV.jl:645
in wavread at /home/juser/.julia/v0.3/WAV/src/WAV.jl:668

I typed the above because copy/paste isn't working from JuliaBox.

I don't think that there is anything wrong with the file. I am able to read it in Adobe Audition and Audacity.

I verified that I can download the posted sample.png, rename to sample.wav and that it is still readable in Adobe Audition.

This .wav file is 16-bit mono at a sampling rate of 24kHz.

I appreciate the work you're doing here. I would greatly appreciate the resolution of this issue.

**Comment by kinord** [comment]
In my opinion, this problem should still be fixed, but there is a work around.

I am able to "clean" the .wav by running it through sox. If I do the following I can then get julia to load sample2.wav.

> sox sample.wav sample2.wav

**Comment by dancasimiro** [comment]
Do you know what is different about the file? 16 bit mono at 24 kHz should work. I will try to read the file later this weekend.

**Comment by kinord** [comment]
My apologies for the slow response. It appears to be working now. Thank you for the quick fix. I did use it right away. I just forgot to respond.
