### ISSUE TITLE
Option to avoid clamp in write_ieee_float_samples()

### ISSUE THREAD

**Issue by Whistler7** [dancasimiro/WAV.jl#23]
I need to be able to write 32-bit and 64-bit IEEE floating-point format WAV files with values outside the [-1,1] range.  The WAV format supports this, and I have been exchanging such files for a long time between Python and REAPER.

In WAV.jl, I see that this function clamps values in such files to [-1, 1] with no user option:
    function write_ieee_float_samples(io::IO, samples, floatType)

When rendering such files to a digital-to-analog converter (DAC), I can see the need for clamping.  In my case, however, there is further processing of the WAV file before the DAC.  This clamping causes a severe distortion for me in many cases.  I propose solving the problem in one of these ways:
1) Gives users of WAV.jl the option of not clamping when writing IEEE floating-point format WAV files.
2) Put the responsibility of clamping IEEE floating-point format WAV files on the rendering side, which makes WAV.jl less complex and easier to test.

**Comment by dancasimiro** [comment]
I think it would be more consistent since I don't clamp float values when reading. I will experiment with removing the clamping from the write function.

**Comment by Whistler7** [comment]
Thanks!

Just to confirm: Does WAV.jl support read and write of 64-bit IEEE floating-point format WAV files?

**Comment by dancasimiro** [comment]
@Whistler7 The library is designed to handle 64 bit floating point data. I added some tests for 64 bit data in a0a95a2. Let me know if you have any trouble.
