### ISSUE TITLE
data=wavread(string) doesn't return Array

### ISSUE THREAD

**Issue by Whistler7** [dancasimiro/WAV.jl#25]
For `data = wavread(string)`, I expect the type of `data` to be `Array{Float64,2}`.  Instead, the type of `data` is `(Array{Float64,2},Uint32,Uint16,UnionType)`.

To work around this problem, I have been doing this: `data, _ = wavread(string)`, where `_` is a throw-away variable, which causes Julia to unpack the tuple.

I suspect you could avoid this problem by changing:

    const result = wavread(io, subrange=subrange, format=format)
    close(io)
    return result

to:

    const samples, sample_rate, nbits, opt = wavread(io, subrange=subrange, format=format)
    close(io)
    return (samples, sample_rate, nbits, opt)

I am new to Julia, so I could be wrong.

**Comment by dancasimiro** [comment]
I don't know if this is possible. I will look into it.

**Comment by dancasimiro** [comment]
I don't think that your proposed change will work as you intend. Julia automatically packs and unpacks tuples when returning multiple values from a function. I think that your example could be:
```julia
data, = wavread(string)
```

I'd be willing to accept a pull request that improves the situation.
