### ISSUE TITLE
Julia 0.4.1 - wavread gives error on 32-bit Linux

### ISSUE THREAD

**Issue by backseatviolist** [dancasimiro/WAV.jl#30]
Using Julia 0.4.1, any call to `wavread` on an existing WAV file (or at least on all the files I've tried so far) results in the following:

    ERROR: InexactError()
     in convert at int.jl:172
     in read_pcm_samples at /home/me/.julia/v0.4/WAV/src/WAV.jl:237
     in read_data at /home/me/.julia/v0.4/WAV/src/WAV.jl:499
     in wavread at /home/me/.julia/v0.4/WAV/src/WAV.jl:618
     in anonymous at /home/me/.julia/v0.4/WAV/src/WAV.jl:628
     in open at iostream.jl:114
     in wavread at /home/me/.julia/v0.4/WAV/src/WAV.jl:627

**Comment by dancasimiro** [comment]
It will be a couple of days before I have time to fix this.

**Comment by dancasimiro** [comment]
@backseatviolist I was not able to reproduce this problem today. Do you have a link to a file that causes the problem? Which version of WAV.jl do you have installed?

**Comment by backseatviolist** [comment]
@dancasimiro Strange, it is working on one machine but not another (both are running Ubuntu with the same version of Julia and the same version of WAV.jl). `Pkg.update(); Pkg.rm("WAV"); Pkg.add("WAV")` didn't fix it. I even removed `~/.julia/` and the problem persists. Something must be screwy with my installation, but I have no idea what.

Attached is a uuencoded WAV file that gives the above error. [test.wav.txt](https://github.com/dancasimiro/WAV.jl/files/44502/test.wav.txt)

**Comment by backseatviolist** [comment]
The problematic line is

    samples[i, j] = convert(eltype(samples), signed(my_sample))

in `read_pcm_samples`. If I println the two arguments to `convert`, running `wavread` on the test file gives this output followed by the error:

    (Int16,0)
    (Int16,0)
    (Int16,0)
    (Int16,0)
    (Int16,1)
    (Int16,4294967294)

It fails because 4294967294 is too large for Int16.

**Comment by dancasimiro** [comment]
That looks like integer overflow. Please try changing:
```
my_sample = unsigned(0)
```
to:
```
my_sample = @compat UInt64(0)
```
in the ```read_pcm_samples``` function. Does it fix the problem on the 32 bit system?

**Comment by backseatviolist** [comment]
Nope, same error.

**Comment by dancasimiro** [comment]
Does Pkg.test("WAV") reproduce the error?

**Comment by dancasimiro** [comment]
Please test commit 561b791. Does it fix the bug? I think that it will, but I don't have a 32 bit CPU to test it on.

**Comment by backseatviolist** [comment]
With the old version, `Pkg.test("WAV")` produces a similar error except with `write_pcm_samples`:

    ERROR: LoadError: InexactError()
     in write_pcm_samples at /home/me/.julia/v0.4/WAV/src/WAV.jl:533
     in write_pcm_samples at /home/me/.julia/v0.4/WAV/src/WAV.jl:550
     in write_data at /home/me/.julia/v0.4/WAV/src/WAV.jl:570
     in wavwrite at /home/me/.julia/v0.4/WAV/src/WAV.jl:713
     [inlined code] from /home/me/.julia/v0.4/WAV/test/runtests.jl:133
     in anonymous at no file:0
     in include at ./boot.jl:261
     in include_from_node1 at ./loading.jl:304
     in process_options at ./client.jl:280
     in _start at ./client.jl:378
    while loading /home/me/.julia/v0.4/WAV/test/runtests.jl, in expression starting on line 122

     in include_from_node1 at ./loading.jl:304
     in process_options at ./client.jl:280
     in _start at ./client.jl:378
    while loading /home/me/.julia/v0.4/WAV/test/runtests.jl, in expression starting on line 122

**Comment by backseatviolist** [comment]
I ran `Pkg.rm("WAV"); Pkg.clone("https://github.com/dancasimiro/WAV.jl.git");`. `wavread` is working now, but `Pkg.test("WAV")` fails with the same error.

**Comment by dancasimiro** [comment]
I pushed a few changes that fix the exceptions on 32 bit systems. However, the 32 bit appveyor tests are still failing the functional tests. Something is broken when the library is trying to encode PCM samples into 64 bits on 32-bit systems. Otherwise, the library appears to work on 32 bit systems. I'm going to keep this issue open until the appveyor tests pass.

FWIW @backseatviolist, you can use "Pkg.checkout" instead of cloning the repository to get an unreleased version.
> help?> Pkg.checkout
>  checkout(pkg, [branch="master"])
>
>  Checkout the Pkg.dir(pkg) repo to the branch branch. Defaults to checking out the "master" branch. To go back to using the newest compatible released version, use Pkg.free(pkg)

**Comment by dancasimiro** [comment]
Commit 681d0e295dd1fb99ea4fdb5729f9550ff84bd5fc fixes the appveyor tests on 32 bit systems. I think that I will tag this revision for release 0.6.2 to fix this issue. Please let me know if it works as expected on your 32 bit system.

**Comment by backseatviolist** [comment]
@dancasimiro  The tests now pass on my system and `wavread` is working as expected. Thanks a bunch!

**Comment by dancasimiro** [comment]
Fixed in WAV.jl version 0.6.2
