### ISSUE TITLE
Writing pre-interleaved stereo recorded data results in a mono file at double fs rate

### ISSUE THREAD

**Issue by wherrera10** [dancasimiro/WAV.jl#32]
I've been using WAV.jl to test some features added to Audio,IO.jl (single stream recording and playback) and ran into a problem with the usual way stereo is recorded on some devices.

If an audio stream is recorded in stereo, the result is generally a single interleaved stream, so the data in the array is not put into a 2D array.  But wavwrite(() then interprets the data as a mono recording when writing the file.

**Comment by dancasimiro** [comment]
Yes, wavwrite uses the dimenions of the matrix as the number of channels. I could add a different interface to support your use case. Another option is to reshape the input array. 

What would you want the interface to look like?

**Comment by wherrera10** [comment]
Reshape is a good idea. Perhaps it would be nice if there were lots of
optional arguments for setting various parameters, but that I suppose would
depend on how it is to be used.

**Comment by wherrera10** [comment]
It needed a bit more than a reshape:

"""
interlaced to noninterlaced stereo data
"""
function deinterlace_stereo(buffer)
    reshape([buffer[1:2:end]; buffer[2:2:end]],
            (floor(Int, length(buffer)/2), 2))
end
