### ISSUE TITLE
ArgumentError in wavappend

### ISSUE THREAD

**Issue by ignacio-vc** [dancasimiro/WAV.jl#35]
Hello, I was trying to run the first example in your Readme. However, it seems to break when using wavappend. I get this error message:

```
julia> wavappend(y, "example.wav")
ERROR: ArgumentError: invalid open mode: rwa
 in open at ./iostream.jl:112
```

**Comment by dancasimiro** [comment]
I'm surprised that you are observing an `ArgumentError`. Does the file exist?
----
Regarding `wavplay`, it does work on Linux. It requires the `libpulse-simple` library. Is that installed on your system? It might be easier to track this in a different issue.

**Comment by ignacio-vc** [comment]
Yes, I have confirmed the file indeed exists. example.wav contains the sine that is first created in the example, but when you want to append the new cosine to it, the aforementioned error message appears. (ArgumentError: invalid open mode: rwa)

And sure, I'll edit the wavplay problem into another issue

**Comment by dancasimiro** [comment]
@ignacio-vc Which version of Julia are you using?

Which version of WAV.jl are you using?
