### ISSUE TITLE
Issue with wavplay on Debian

### ISSUE THREAD

**Issue by ignacio-vc** [dancasimiro/WAV.jl#36]
When I try to use wavplay, I get the message that it is not currently implemented on Linux. I thought this was the case on Windows and that it worked fine on Linux? Or am I mistaken there?

I'm running Julia 0.4.5 on Debian Sid, in case that helps

**Comment by ignacio-vc** [comment]
Update: I have installed the libpulse-dev package, which seems to contain the needed libpulse-simple.

Now when I try to use wavplay on the sine example, I get this output:

```

WARNING: convert(::Type{Ptr}, ::Int64) methods should be converted to be methods of unsafe_convert
 in depwarn at ./deprecated.jl:73
while loading no file, in expression starting on line 0
WARNING: convert(::Type{Ptr}, ::Int64) methods should be converted to be methods of unsafe_convert
 in depwarn at ./deprecated.jl:73
while loading no file, in expression starting on line 0
WARNING: convert(::Type{Ptr}, ::Int64) methods should be converted to be methods of unsafe_convert
 in depwarn at ./deprecated.jl:73
while loading no file, in expression starting on line 0
WARNING: convert(::Type{Ptr}, ::Int64) methods should be converted to be methods of unsafe_convert
 in depwarn at ./deprecated.jl:73
while loading no file, in expression starting on line 0

```

**Comment by dancasimiro** [comment]
I will try to provide a better error message and take care of those deprecation warnings.

**Comment by pvazteixeira** [comment]
Hi,

I'm running WAV.jl on Julia 0.5 and Debian Jessie (8.6), and get the following error messages when attempting to run 'wavplay':

`
julia> wavplay(y, fs)
ERROR: MethodError: no method matching unsafe_convert(::Type{Ptr{Void}}, ::Int64)
Closest candidates are:
  unsafe_convert{T}(::Type{Ptr{Void}}, ::Base.RefValue{T}) at refpointer.jl:49
  unsafe_convert{T}(::Type{Ptr{Void}}, ::Base.RefArray{T,A<:AbstractArray,R}) at refpointer.jl:73
  unsafe_convert(::Type{Ptr{Void}}, ::IOStream) at iostream.jl:27
  ...
 in wavplay(::Array{Float64,1}, ::Int64) at /home/pvt/.julia/v0.5/WAV/src/wavplay-pulse.jl:16
`

I do have libpulse-dev installed.

**Comment by dancasimiro** [comment]
That looks like a different bug. Something broke against Julia 0.5.0. I won't have time to investigate until this weekend, at the earliest.

**Comment by dancasimiro** [comment]
@pvazteixeira I created issue #39 to track your problem.

**Comment by pvazteixeira** [comment]
@dancasimiro Thanks -- please let me know how I can help.
