### ISSUE TITLE
Memory-mapping in `wavread`?

### ISSUE THREAD

**Issue by dmbates** [dancasimiro/WAV.jl#42]
When `wavread` is called on a file it seems worthwhile memory-mapping the samples in the file.  I don't have experience WAV file other than in PCM encoding but certainly for them memory-mapping seems much faster than reading the file as in `read_pcm_samples`.

**Comment by dancasimiro** [comment]
I don't plan to implement this feature, but pull requests are welcome.

**Comment by dancasimiro** [comment]
One complication is that the current implementation supports arbitrtary integer widths. An mmap solution won't easily support 24 bit integers on a platform without an equivalent data type.

**Comment by dmbates** [comment]
It turns out that I can by-pass the issue.  I went back and read the man page for `icedax` and found that it can save tracks from an audio CD as `.cda`, which is just the data chunk.  Because I know the format of the data chunk I can memory map the `.cda` file and avoid working with any `.wav` files.

I agree that memory-mapping is problematic for 24 bit samples.
