### ISSUE TITLE
is there an option to read into a mono?

### ISSUE THREAD

**Issue by EMCP** [dancasimiro/WAV.jl#53]
I am working on porting a project that just analyzes the mono singles of audio samples..

Not sure how it was done in Python, but now trying to just get a working copy of my workflow into Julialang.. is there a quick way to indicate I want to read the wav into a mono?

Thanks for this library, I haven't found a lot of audio processing other than this library.

**Comment by dancasimiro** [comment]
Do you want the library to read one of the channels or mix all the channels together?

**Comment by EMCP** [comment]
I am attempting to measure the difference between an audio sample.. and another.

I think the mix would be the first choice since there could be panning being performed... For reference this is the project I'm porting.. I have a personal version in python3

https://github.com/kylemcdonald/AudioNotebooks

The particular call they perform is using FFMPEG.. I'd guess they'd mix 

https://github.com/kylemcdonald/AudioNotebooks/blob/master/Collect%20Samples.ipynb
