### ISSUE TITLE
Unable to write multiple LIST chunks

### ISSUE THREAD

**Issue by rkat** [dancasimiro/WAV.jl#55]
With the current API it's not possible to write multiple chunks of the same type. This is needed e.g. for writing a .wav file that contains both a LIST chunk for the INFO chunk and another one for the cue points. 

I propose that `wavwrite` be updated as follows:
```julia
wavwrite(samples::AbstractArray, io::IO; Fs=8000, nbits=0, compression=0,
                  chunks::Vector{Tuple{Symbol, Array{UInt8,1}}}=Tuple{Symbol, Array{UInt8,1}}[])
```
This would allow multiple LIST chunks to be written, and also allow the order of chunks written to be specified (at the moment it depends on Julia's hashing) but it will be a breaking change to the API. We'll have to change `wavread` as well - we can make it return a `Vector{Tuple{Symbol, Array{UInt8,1}}` or a `Dict{Symbol, Vector{Any}}` where the entries in the dictionary are vectors containing all the chunks with a particular ID. I'd tend to go with the first option because it means you could read/write chunks without having to convert between the two types.

@dancasimiro if you approve of this change then I'm happy to implement and test it. If not, let me know your thoughts on other options.

**Comment by dancasimiro** [comment]
Fixed by pull request #56, but still waiting for documentation updates.

**Comment by rkat** [comment]
Thanks Dan. I've updated the docs. Feel free to edit as you see fit 😄

**Comment by dancasimiro** [comment]
I am going to wait for other breaking changes before publishing v1.0.0 of the WAV library. I would also like to wait until the FileIO.jl package is updated to support the newest Julia.
