### ISSUE TITLE
Support Julia v0.7? 

### ISSUE THREAD

**Issue by rdeits** [dancasimiro/WAV.jl#66]
I don't think there are any released versions of WAV.jl that support Julia 0.7, which makes it harder to migrate any code that uses this package. The typical migration path is v0.6.4 -> v0.7 -> fix deprecations -> v1.0, but that's not possible if WAV.jl doesn't support v0.7. 

Would you be willing to drop the required version to 0.7? I don't think there's any downside to doing so.

**Comment by dancasimiro** [comment]
Sorry, I messed this up rushing out a version that supports Julia v1.0. What are my options? Can I release WAV.jl v1.0.1 that claims to support Julia v0.7 and Julia v1.0? It's the same code so should be ok... However, I don't know the ins and outs of Pkg3.

**Comment by rdeits** [comment]
Heh, that's a good question. I just posted over in `#helpdesk` on slack, so perhaps someone there knows. I'd suggest merging #68 regardless, since that will at least get CI working again.

**Comment by dancasimiro** [comment]
thanks @rdeits

#68 is merged; I had to resolve a minor conflict with a commit from Femto Cleaner.

**Comment by quinnj** [comment]
yeah, we originally made this mistake w/ Missings.jl, where the lower julia version was put as 1.0 instead of 0.7.

**Comment by dancasimiro** [comment]
I’ll try to take a look at the history of Missings.jl this weekend.

**Comment by bjarthur** [comment]
i get this warning in julia 0.7:

```
WARNING: importing deprecated binding Base.Libdl into WAV.
WARNING: Base.Libdl is deprecated, run `using Libdl` instead
  likely near /Users/arthurb/.julia/packages/WAV/npPEy/src/WAV.jl:780
```

i think to support 0.7 the REQUIRES file simply needs to be changed, and any depwarns like the above fixed.

**Comment by bjarthur** [comment]
ah, i see you've done this on master.  might want to tag a release.

**Comment by dancasimiro** [comment]
@bjarthur I tagged v1.0.1 with this fix.  See JuliaLang/METADATA.jl#20253
