### ISSUE TITLE
Playing with @async is blocking

### ISSUE THREAD

**Issue by gstavrinos** [dancasimiro/WAV.jl#73]
Hey Daniel,

I have a MWE for my problem:

```
using WAV
y, fs = wavread("sound.wav")
@async wavplay(y, fs)
while true println("async!") end
```

I would expect to see multiple `"async!"` messages, but I see only one. Any thoughs?

Thanks

**Comment by dancasimiro** [comment]
Which wavplay implemention are you using? Is it the pulse audio implementation or the native macOS implementation?

**Comment by gstavrinos** [comment]
Oh, yeah, sorry. I am on Ubuntu 18.04, so pulse audio!

**Comment by gstavrinos** [comment]
Any updates on this?

**Comment by dancasimiro** [comment]
I’m sorry, but I don’t have time to track this issue down. I am accepting pull requests though.

**Comment by gstavrinos** [comment]
Sure, no problem. I'll see what I can do, but my schedule is tight too! Thank you!

**Comment by mgkuhn** [comment]
`@async` just creates a task (for co-routines) and does not run it in another thread, so your example works sequentially (single-threaded), as expected.

For what you wanted, try to spawn a task into an available thread:
```
$ cat test.jl
using WAV
using Base.Threads
y, fs = wavread("example.wav")
Threads.@spawn wavplay(y, fs)
while true println("async!") end
$ JULIA_NUM_THREADS=2 julia test.jl
```
Note that `Threads.@spawn` is still an experimental feature as of Julia 1.4.

What I think you probably really wanted: if a backend provides asynchronous playback (i.e., tell the C function call to return immediately), we could expose this to the user e.g. as `wavplay(y, fs; async=true)`.

The Windows backend apparently can do this: we just need to replace the flag `SND_SYNC` with `SND_ASYNC`. I don't know yet about the other backends.

**Comment by dancasimiro** [comment]
closing due to lack of follow up
